---
name: Published release
on:
  release:
    types:
      - published
permissions: {}
jobs:
  close-milestone:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close milestone
        run: |
          set -eu

          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{github.token}}
