---
name: Published release
on:
  release:
    types:
      - published
permissions: {}
jobs:
  close-milestone:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close milestone
        run: |
          set -eu

          milestones=$(gh api -X GET /repos/${{github.repository}}/milestones -f state=all)
          milestone_number=$(echo "${milestones}" | jq ". | map(select(.title == \"${{ github.ref_name }}\")) | first | .number")
          gh api -X PATCH "repos/${{github.repository}}/milestones/$milestone_number" -f state=closed
        env:
          GITHUB_TOKEN: ${{github.token}}
